apiVersion: v1
kind: Service
metadata:
  labels:
    app: redic
  name: redic
spec:
  ports:
    - name: "6379"
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redic
  type: ClusterIP
