apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - merge.yml
resources:
  - ../../base
replicas:
  - name: vote
    count: 3
images:
  - name: schoolofdevops/vote
    newTag: main-a0384b9f-1667833949 # {"$imagepolicy": "flux-system:vote:tag"}
commonLabels:
  project: instavote
  environment: staging
  team: devops
commonAnnotations:
  note: This is a staging environment
  team: devops
configMapGenerator:
  - name: vote-options
    envs:
      - options.env
namespace: instavote
