apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: vote
    count: 3
images:
  - name: schoolofdevops/vote
    newTag: v1
commonLabels:
  project: instavote
  environment: staging
  team: devops
commonAnnotations:
  note: This is a staging environment
  team: devops
