apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 3
  template:
    spec:
      containers:
        - image: schoolofdevops/vote:v5
          name: vote
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  ports:
    - name: "80"
      nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: vote
  type: LoadBalancer
