apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 3
  template:
    spec:
      containers:
        - image: schoolofdevops/vote:v5
          name: vote
          resources: {}
