apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  project: instavote
  environment: staging
  team: devops
commonAnnotations:
  note: This is a staging environment
  team: devops
